### PR TITLE
Support for Spanish Locale

### PR DESCRIPTION
**Pull request by gabrielcalderon**
* Updated fxmanifest.lua
* Create locale/es.lua

Note: I didn't create a Spanish SQL file since I think those should be edited by the server owners.

### CODE REVIEW

**Comment by gabrielcalderon** [comment]
@VictorNJ21 If you clicked "Merge Pull Request", it would do everything for you. Now my changes are in a limbo state.

**Comment by VictorNJ21** [comment]
Oh lol, my bad. I'm quite new to Github. What we do now? Haha

**Comment by VictorNJ21** [comment]
Oh, nvm, think I got it now.

**Comment by gabrielcalderon** [comment]
@VictorNJ21 Perfect! Thanks 👍 If I find anything else, I will do another Merge request.

**Pull request merged**
